CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++17

NAME = scav

SRC =	ClapTrap.cpp \
		ScavTrap.cpp \
		main.cpp
OBJ = $(SRC:.cpp=.o)

$(NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $(NAME) $(OBJ)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean $(NAME)

.PHONY: clean fclean re
